name: Bug report
description: Create a report to help me improve the plugin
title: '[Bug]: '
assignees:
  - spartacus04
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Stepts to reproduce the behaviour
      placeholder: 1. Go to '...'  2. Click on '....' 3. Scroll down to '....' 4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Logs
      description: If applicable, upload the error logs (use something like mclo.gs).
  - type: dropdown
    id: serverversion
    attributes:
      label: Server Version
      description: Select the server version
      options:
        - 1.20.1
        - '1.20'
        - 1.19.4
        - 1.19.3
        - 1.19.2
        - 1.19.1
        - '1.19'
        - 1.18.2
        - 1.18.1
        - '1.18'
        - 1.17.1
        - '1.17'
        - 1.16.5
        - 1.16.4
        - 1.16.3
        - 1.16.2
        - 1.16.1
        - '1.16'
        - 1.15.2
        - 1.15.1
        - '1.15'
        - 1.14.4
        - 1.14.3
        - 1.14.2
        - 1.14.1
        - '1.14'
    validations:
      required: true
  - type: dropdown
    id: ServerType
    attributes:
      label: Server Type
      description: Select the server type
      options:
        - Spigot
        - Paper
        - Purpur
        - Folia
    validations:
      required: true
  - type: textarea
    id: discsjson
    attributes:
      label: Discs.json
      description: If you want to, you can upload your discs.json file for further detail
      render: json
  - type: input
    id: rp
    attributes:
      label: Resource pack
      description: >-
        If you want to, you can upload your resource pack file for further
        detail
  - type: dropdown
    id: JukeboxMode
    attributes:
      label: Jukebox Behaviour
      description: Which jukebox behaviour are you using? (legacy-gui is not supported, just switch to gui)
      options:
        - Vanilla
        - Gui
    validations:
      required: true
  - type: checkboxes
    id: Checkboxes
    attributes:
      label: Before submitting the issue
      options:
        - label: >-
            I have searched the issue tracker and did not find an issue
            describing my bug.
          required: true
        - label: >-
            I agree to the fact that if this issue becomes inactive it will be
            closed.
          required: true
        - label: >-
            I agree to the fact that if most fields in this issue are not filled correctly
            the issue will be marked as invalid and closed.
          required: true
