name: Generator Bug report
description: Create a report to help me improve the generator
title: '[Bug]: '
assignees:
  - spartacus04
labels:
  - bug
  - generator
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Stepts to reproduce the behaviour
      placeholder: 1. Go to '...'  2. Click on '....' 3. Scroll down to '....' 4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, check the browser developer console and paste the error logs
  - type: checkboxes
    id: Checkboxes
    attributes:
      label: Before submitting the issue
      options:
        - label: >-
            I have searched the issue tracker and did not find an issue
            describing my bug.
          required: true
        - label: >-
            I agree to the fact that if this issue becomes inactive it will be
            closed.
          required: true
        - label: >-
            I agree to the fact that if most fields in this issue are not filled correctly
            the issue will be marked as invalid and closed.
          required: true

